
uav.constraints.velocity.x = 4; % [m/s]
uav.constraints.velocity.y = 4; % [m/s]
uav.constraints.velocity.z = 4; % [m/s]

G_out_max = [Cdbar];
S_out_max = [-Adhat];

W_out_max = repmat([Inf, Inf, Inf, deg2rad(45) deg2rad(45) Inf...
    uav.constraints.velocity.x...
    uav.constraints.velocity.y...
    uav.constraints.velocity.z...
    5 5 5 umax']',N,1); % 
W_out_min = repmat(-[-Inf, -Inf, -Inf, -deg2rad(45) -deg2rad(45) -Inf...
    -uav.constraints.velocity.x...
    -uav.constraints.velocity.y...
    -uav.constraints.velocity.z...
    -5 -5 -5 umin']',N,1); % 

G_out = [G_out_max;-G_out_max];    
W_out = [W_out_max; W_out_min];
S_out = [S_out_max;-S_out_max];